### ISSUE TITLE
NilClass#edit (ActionView::Template::Error) "undefined method `name' for nil:NilClass"

### ISSUE THREAD

**Issue by rastyagaev** [enot-kg/enot#18]
<table><tr><th>Exception</th><td>undefined method `name&#39; for nil:NilClass</td></tr><tr><th>Last Occurrence</th><td>November 16, 2017 15:42:02 +0600</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/enot-kg/enot/blob/0f144107115c36a32a139c8516e4ec238349334c/app/views/management/reviews/_form.html.erb#L7'>[app].../app/views/management/reviews/_form.html.erb:7:in `block (2 levels) in _app_views_management_reviews__form_html_erb__2249493134418768779_70485660'</a>
[bundle].../gems/actionpack-4.0.1/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
[bundle].../gems/actionpack-4.0.1/lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
[bundle].../gems/actionpack-4.0.1/lib/action_view/helpers/capture_helper.rb:38:in `capture'
[bundle].../gems/simple_form-3.0.0/lib/simple_form/inputs/block_input.rb:10:in `input'
[bundle].../gems/simple_form-3.0.0/lib/simple_form/components/label_input.rb:11:in `label_input'
[bundle].../gems/simple_form-3.0.0/lib/simple_form/wrappers/many.rb:29:in `block in render'
[bundle].../gems/simple_form-3.0.0/lib/simple_form/wrappers/many.rb:27:in `each'
[bundle].../gems/simple_form-3.0.0/lib/simple_form/wrappers/many.rb:27:in `render'
[bundle].../gems/simple_form-3.0.0/lib/simple_form/wrappers/root.rb:15:in `render'
[bundle].../gems/simple_form-3.0.0/lib/simple_form/form_builder.rb:120:in `input'
<a href='https://github.com/enot-kg/enot/blob/0f144107115c36a32a139c8516e4ec238349334c/app/views/management/reviews/_form.html.erb#L5'>[app].../app/views/management/reviews/_form.html.erb:5:in `block in _app_views_management_reviews__form_html_erb__2249493134418768779_70485660'</a>
[bundle].../gems/actionpack-4.0.1/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
[bundle].../gems/actionpack-4.0.1/lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
[bundle].../gems/actionpack-4.0.1/lib/action_view/helpers/capture_helper.rb:38:in `capture'
[bundle].../gems/actionpack-4.0.1/lib/action_view/helpers/form_helper.rb:435:in `form_for'
[bundle].../gems/simple_form-3.0.0/lib/simple_form/action_view_extensions/form_helper.rb:22:in `block in simple_form_for'
[bundle].../gems/simple_form-3.0.0/lib/simple_form/action_view_extensions/form_helper.rb:41:in `with_simple_form_field_error_proc'
[bundle].../gems/simple_form-3.0.0/lib/simple_form/action_view_extensions/form_helper.rb:21:in `simple_form_for'
<a href='https://github.com/enot-kg/enot/blob/0f144107115c36a32a139c8516e4ec238349334c/app/views/management/reviews/_form.html.erb#L1'>[app].../app/views/management/reviews/_form.html.erb:1:in `_app_views_management_reviews__form_html_erb__2249493134418768779_70485660'</a>
[bundle].../gems/actionpack-4.0.1/lib/action_view/template.rb:143:in `block in render'
[bundle].../gems/activesupport-4.0.1/lib/active_support/notifications.rb:161:in `instrument'
[bundle].../gems/actionpack-4.0.1/lib/action_view/template.rb:141:in `render'
[bundle].../gems/actionpack-4.0.1/lib/action_view/renderer/partial_renderer.rb:306:in `render_partial'
[bundle].../gems/actionpack-4.0.1/lib/action_view/renderer/partial_renderer.rb:279:in `block in render'
[bundle].../gems/actionpack-4.0.1/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
[bundle].../gems/activesupport-4.0.1/lib/active_support/notifications.rb:159:in `block in instrument'
[bundle].../gems/activesupport-4.0.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.0.1/lib/active_support/notifications.rb:159:in `instrument'
[bundle].../gems/actionpack-4.0.1/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
[bundle].../gems/actionpack-4.0.1/lib/action_view/renderer/partial_renderer.rb:278:in `render'
[bundle].../gems/actionpack-4.0.1/lib/action_view/renderer/renderer.rb:47:in `render_partial'
[bundle].../gems/actionpack-4.0.1/lib/action_view/helpers/rendering_helper.rb:27:in `render'
<a href='https://github.com/enot-kg/enot/blob/0f144107115c36a32a139c8516e4ec238349334c/app/views/management/edit.html.erb#L13'>[app].../app/views/management/edit.html.erb:13:in `_app_views_management_edit_html_erb___967630588169177472_70214060'</a>
[bundle].../gems/actionpack-4.0.1/lib/action_view/template.rb:143:in `block in render'
[bundle].../gems/activesupport-4.0.1/lib/active_support/notifications.rb:161:in `instrument'
[bundle].../gems/actionpack-4.0.1/lib/action_view/template.rb:141:in `render'
[bundle].../gems/actionpack-4.0.1/lib/action_view/renderer/template_renderer.rb:49:in `block (2 levels) in render_template'
[bundle].../gems/actionpack-4.0.1/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
[bundle].../gems/activesupport-4.0.1/lib/active_support/notifications.rb:159:in `block in instrument'
[bundle].../gems/activesupport-4.0.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.0.1/lib/active_support/notifications.rb:159:in `instrument'
[bundle].../gems/actionpack-4.0.1/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
[bundle].../gems/actionpack-4.0.1/lib/action_view/renderer/template_renderer.rb:48:in `block in render_template'
[bundle].../gems/actionpack-4.0.1/lib/action_view/renderer/template_renderer.rb:56:in `render_with_layout'
[bundle].../gems/actionpack-4.0.1/lib/action_view/renderer/template_renderer.rb:47:in `render_template'
[bundle].../gems/actionpack-4.0.1/lib/action_view/renderer/template_renderer.rb:17:in `render'
[bundle].../gems/actionpack-4.0.1/lib/action_view/renderer/renderer.rb:42:in `render_template'
[bundle].../gems/actionpack-4.0.1/lib/action_view/renderer/renderer.rb:23:in `render'
[bundle].../gems/actionpack-4.0.1/lib/abstract_controller/rendering.rb:127:in `_render_template'
[bundle].../gems/actionpack-4.0.1/lib/action_controller/metal/streaming.rb:219:in `_render_template'
[bundle].../gems/actionpack-4.0.1/lib/abstract_controller/rendering.rb:120:in `render_to_body'
[bundle].../gems/actionpack-4.0.1/lib/action_controller/metal/rendering.rb:33:in `render_to_body'
[bundle].../gems/actionpack-4.0.1/lib/action_controller/metal/renderers.rb:26:in `render_to_body'
[bundle].../gems/actionpack-4.0.1/lib/abstract_controller/rendering.rb:97:in `render'
[bundle].../gems/actionpack-4.0.1/lib/action_controller/metal/rendering.rb:16:in `render'
[bundle].../gems/actionpack-4.0.1/lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
[bundle].../gems/activesupport-4.0.1/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
<a href='https://github.com/enot-kg/enot/blob/0f144107115c36a32a139c8516e4ec238349334c/vendor/ruby-2.3.4/lib/ruby/2.3.0/benchmark.rb#L308'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'</a>
[bundle].../gems/activesupport-4.0.1/lib/active_support/core_ext/benchmark.rb:12:in `ms'
[bundle].../gems/actionpack-4.0.1/lib/action_controller/metal/instrumentation.rb:41:in `block in render'
[bundle].../gems/actionpack-4.0.1/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
[bundle].../gems/activerecord-4.0.1/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
[bundle].../gems/actionpack-4.0.1/lib/action_controller/metal/instrumentation.rb:40:in `render'
[bundle].../gems/actionpack-4.0.1/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
[bundle].../gems/actionpack-4.0.1/lib/action_controller/metal/responder.rb:233:in `default_render'
[bundle].../gems/actionpack-4.0.1/lib/action_controller/metal/responder.rb:161:in `to_html'
[bundle].../gems/actionpack-4.0.1/lib/action_controller/metal/responder.rb:154:in `respond'
[bundle].../gems/actionpack-4.0.1/lib/action_controller/metal/responder.rb:147:in `call'
[bundle].../gems/actionpack-4.0.1/lib/action_controller/metal/mime_responds.rb:330:in `respond_with'
<a href='https://github.com/enot-kg/enot/blob/0f144107115c36a32a139c8516e4ec238349334c/app/controllers/concerns/managment/resources.rb#L41'>[app].../app/controllers/concerns/managment/resources.rb:41:in `edit'</a>
[bundle].../gems/actionpack-4.0.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-4.0.1/lib/abstract_controller/base.rb:189:in `process_action'
[bundle].../gems/actionpack-4.0.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-4.0.1/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
[bundle].../gems/activesupport-4.0.1/lib/active_support/callbacks.rb:413:in `_run__573870520274481084__process_action__callbacks'
[bundle].../gems/activesupport-4.0.1/lib/active_support/callbacks.rb:80:in `run_callbacks'
[bundle].../gems/actionpack-4.0.1/lib/abstract_controller/callbacks.rb:17:in `process_action'
[bundle].../gems/actionpack-4.0.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-4.0.1/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
[bundle].../gems/activesupport-4.0.1/lib/active_support/notifications.rb:159:in `block in instrument'
[bundle].../gems/activesupport-4.0.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.0.1/lib/active_support/notifications.rb:159:in `instrument'
[bundle].../gems/actionpack-4.0.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[bundle].../gems/actionpack-4.0.1/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
[bundle].../gems/activerecord-4.0.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/actionpack-4.0.1/lib/abstract_controller/base.rb:136:in `process'
[bundle].../gems/actionpack-4.0.1/lib/abstract_controller/rendering.rb:44:in `process'
[bundle].../gems/actionpack-4.0.1/lib/action_controller/metal.rb:195:in `dispatch'
[bundle].../gems/actionpack-4.0.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
[bundle].../gems/actionpack-4.0.1/lib/action_controller/metal.rb:231:in `block in action'
[bundle].../gems/actionpack-4.0.1/lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
[bundle].../gems/actionpack-4.0.1/lib/action_dispatch/routing/route_set.rb:48:in `call'
[bundle].../gems/actionpack-4.0.1/lib/action_dispatch/journey/router.rb:71:in `block in call'
[bundle].../gems/actionpack-4.0.1/lib/action_dispatch/journey/router.rb:59:in `each'
[bundle].../gems/actionpack-4.0.1/lib/action_dispatch/journey/router.rb:59:in `call'
[bundle].../gems/actionpack-4.0.1/lib/action_dispatch/routing/route_set.rb:680:in `call'
[bundle].../gems/omniauth-1.1.4/lib/omniauth/strategy.rb:184:in `call!'
[bundle].../gems/omniauth-1.1.4/lib/omniauth/strategy.rb:164:in `call'
[bundle].../gems/party_foul-1.5.1/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/etag.rb:23:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/conditionalget.rb:25:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/head.rb:11:in `call'
[bundle].../gems/actionpack-4.0.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[bundle].../gems/actionpack-4.0.1/lib/action_dispatch/middleware/flash.rb:241:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/session/abstract/id.rb:225:in `context'
[bundle].../gems/rack-1.5.5/lib/rack/session/abstract/id.rb:220:in `call'
[bundle].../gems/actionpack-4.0.1/lib/action_dispatch/middleware/cookies.rb:486:in `call'
[bundle].../gems/activerecord-4.0.1/lib/active_record/query_cache.rb:36:in `call'
[bundle].../gems/activerecord-4.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
[bundle].../gems/actionpack-4.0.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[bundle].../gems/activesupport-4.0.1/lib/active_support/callbacks.rb:373:in `_run__4597071713051603659__call__callbacks'
[bundle].../gems/activesupport-4.0.1/lib/active_support/callbacks.rb:80:in `run_callbacks'
[bundle].../gems/actionpack-4.0.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/actionpack-4.0.1/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
[bundle].../gems/actionpack-4.0.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[bundle].../gems/actionpack-4.0.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[bundle].../gems/railties-4.0.1/lib/rails/rack/logger.rb:38:in `call_app'
[bundle].../gems/railties-4.0.1/lib/rails/rack/logger.rb:20:in `block in call'
[bundle].../gems/activesupport-4.0.1/lib/active_support/tagged_logging.rb:67:in `block in tagged'
[bundle].../gems/activesupport-4.0.1/lib/active_support/tagged_logging.rb:25:in `tagged'
[bundle].../gems/activesupport-4.0.1/lib/active_support/tagged_logging.rb:67:in `tagged'
[bundle].../gems/railties-4.0.1/lib/rails/rack/logger.rb:20:in `call'
[bundle].../gems/actionpack-4.0.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'
[bundle].../gems/activesupport-4.0.1/lib/active_support/cache/strategy/local_cache.rb:83:in `call'
[bundle].../gems/actionpack-4.0.1/lib/action_dispatch/middleware/static.rb:64:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/sendfile.rb:112:in `call'
[bundle].../gems/railties-4.0.1/lib/rails/engine.rb:511:in `call'
[bundle].../gems/railties-4.0.1/lib/rails/application.rb:97:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/lock.rb:17:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/content_length.rb:14:in `call'
[bundle].../gems/rack-1.5.5/lib/rack/handler/webrick.rb:60:in `service'
<a href='https://github.com/enot-kg/enot/blob/0f144107115c36a32a139c8516e4ec238349334c/vendor/ruby-2.3.4/lib/ruby/2.3.0/webrick/httpserver.rb#L140'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'</a>
<a href='https://github.com/enot-kg/enot/blob/0f144107115c36a32a139c8516e4ec238349334c/vendor/ruby-2.3.4/lib/ruby/2.3.0/webrick/httpserver.rb#L96'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'</a>
<a href='https://github.com/enot-kg/enot/blob/0f144107115c36a32a139c8516e4ec238349334c/vendor/ruby-2.3.4/lib/ruby/2.3.0/webrick/server.rb#L296'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'</a></pre>
Fingerprint: `1841fbd854ad8222ef825e466aceb60fecde8e7b`

**Comment by rastyagaev** [comment]
<table><tr><th>Occurred At</th><td>November 16, 2017 15:42:02 +0600</td></tr><tr><th>URL</th><td>[GET] http://enot-kg.herokuapp.com/management/reviews/2/edit</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>edit</td></tr><tr><th>controller</th><td>management/reviews</td></tr><tr><th>id</th><td>2</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>78.140.205.190</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8</td></tr></table></td></tr></table>
